name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/secrets-cli-linux-amd64
          GOOS=linux   GOARCH=arm64 go build -o dist/secrets-cli-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/secrets-cli-windows-amd64.exe
          GOOS=darwin  GOARCH=amd64 go build -o dist/secrets-cli-darwin-amd64
          GOOS=darwin  GOARCH=arm64 go build -o dist/secrets-cli-darwin-arm64
          cd dist
          zip secrets-cli-linux-amd64.zip secrets-cli-linux-amd64
          zip secrets-cli-linux-arm64.zip secrets-cli-linux-arm64
          zip secrets-cli-windows-amd64.zip secrets-cli-windows-amd64.exe
          zip secrets-cli-darwin-amd64.zip secrets-cli-darwin-amd64
          zip secrets-cli-darwin-arm64.zip secrets-cli-darwin-arm64

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/secrets-cli-linux-amd64.zip
            dist/secrets-cli-linux-arm64.zip
            dist/secrets-cli-windows-amd64.zip
            dist/secrets-cli-darwin-amd64.zip
            dist/secrets-cli-darwin-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
